[0m15:36:14.857392 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E239A94CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E23D929310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E23D6EF440>]}


============================== 15:36:14.865392 | ac66b7dc-bb94-4820-9ab4-626c1fdda842 ==============================
[0m15:36:14.865392 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:36:14.866359 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt build', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'False', 'quiet': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\VaishnaviRajput\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m15:36:14.876466 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\VaishnaviRajput\Downloads\Github\dbt-dagster\dagster-dbt-poc\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:36:14.878486 [debug] [MainThread]: Command `dbt build` failed at 15:36:14.878486 after 0.51 seconds
[0m15:36:14.879477 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E23D7C0A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E23D8F0770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E23DC200B0>]}
[0m15:36:14.879477 [debug] [MainThread]: Flushing usage events
[0m15:36:15.661692 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:36:37.854505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017439E7D7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001743B4571A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001743DA1E540>]}


============================== 15:36:37.861503 | db5d689c-cefb-4544-bf52-19885da7962f ==============================
[0m15:36:37.861503 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:36:37.863825 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'warn_error': 'None', 'invocation_command': 'dbt seed', 'log_format': 'default', 'use_colors': 'True', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'fail_fast': 'False', 'no_print': 'None', 'empty': 'None', 'quiet': 'False', 'printer_width': '80', 'use_experimental_parser': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\VaishnaviRajput\\.dbt', 'static_parser': 'True', 'write_json': 'True'}
[0m15:36:37.863825 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\VaishnaviRajput\Downloads\Github\dbt-dagster\dagster-dbt-poc\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:36:37.865856 [debug] [MainThread]: Command `dbt seed` failed at 15:36:37.864845 after 0.51 seconds
[0m15:36:37.865856 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001743D5F6EA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001743D858D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001743D858C80>]}
[0m15:36:37.866844 [debug] [MainThread]: Flushing usage events
[0m15:36:38.497860 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:38:12.511996 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E1D24CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E54D89E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E2AC8860>]}


============================== 15:38:12.520056 | 64ee6bb2-e545-4941-b2a5-091fdaa3e909 ==============================
[0m15:38:12.520056 [info ] [MainThread]: Running with dbt=1.10.11
[0m15:38:12.522256 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True', 'warn_error': 'None', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'use_experimental_parser': 'False', 'empty': 'None', 'log_cache_events': 'False', 'quiet': 'False', 'indirect_selection': 'eager', 'log_path': 'logs', 'write_json': 'True', 'static_parser': 'True', 'profiles_dir': 'C:\\Users\\VaishnaviRajput\\.dbt'}
[0m15:38:12.563930 [info ] [MainThread]: dbt version: 1.10.11
[0m15:38:12.565678 [info ] [MainThread]: python version: 3.12.10
[0m15:38:12.566745 [info ] [MainThread]: python path: C:\Users\VaishnaviRajput\Downloads\Github\dbt-dagster\dagster-dbt-poc\venv\Scripts\python.exe
[0m15:38:12.567289 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:38:12.568360 [info ] [MainThread]: Using profiles dir at C:\Users\VaishnaviRajput\.dbt
[0m15:38:12.568889 [info ] [MainThread]: Using profiles.yml file at C:\Users\VaishnaviRajput\.dbt\profiles.yml
[0m15:38:12.569418 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\VaishnaviRajput\Downloads\Github\dbt-dagster\dagster-dbt-poc\dbt_project.yml
[0m15:38:12.569946 [info ] [MainThread]: Configuration:
[0m15:38:12.570474 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m15:38:12.571002 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:38:12.571539 [info ] [MainThread]: Required dependencies:
[0m15:38:12.572079 [debug] [MainThread]: Executing "git --help"
[0m15:38:12.782961 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m15:38:12.783953 [debug] [MainThread]: STDERR: "b''"
[0m15:38:12.783953 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m15:38:12.784789 [info ] [MainThread]: Connection test skipped since no profile was found
[0m15:38:12.785804 [info ] [MainThread]: [31m2 checks failed:[0m
[0m15:38:12.786799 [info ] [MainThread]: dbt looked for a profiles.yml file in C:\Users\VaishnaviRajput\.dbt\profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m15:38:12.786799 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\VaishnaviRajput\Downloads\Github\dbt-dagster\dagster-dbt-poc\dbt_project.yml> not found

[0m15:38:12.788801 [debug] [MainThread]: Command `dbt debug` failed at 15:38:12.788801 after 0.78 seconds
[0m15:38:12.788801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E5AA0D70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E57B69C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196E57B6E40>]}
[0m15:38:12.789803 [debug] [MainThread]: Flushing usage events
[0m15:38:13.473892 [debug] [MainThread]: An error was encountered while trying to flush usage events
